// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdjustStock(arg1) {
  return window['go']['main']['App']['AdjustStock'](arg1);
}

export function ApplyIncomingMutations(arg1, arg2) {
  return window['go']['main']['App']['ApplyIncomingMutations'](arg1, arg2);
}

export function AuthenticateStaff(arg1) {
  return window['go']['main']['App']['AuthenticateStaff'](arg1);
}

export function BackendHealth() {
  return window['go']['main']['App']['BackendHealth']();
}

export function BootstrapBusiness(arg1) {
  return window['go']['main']['App']['BootstrapBusiness'](arg1);
}

export function CreateCategory(arg1) {
  return window['go']['main']['App']['CreateCategory'](arg1);
}

export function CreateProduct(arg1) {
  return window['go']['main']['App']['CreateProduct'](arg1);
}

export function CreateSale(arg1) {
  return window['go']['main']['App']['CreateSale'](arg1);
}

export function CreateStaff(arg1) {
  return window['go']['main']['App']['CreateStaff'](arg1);
}

export function DashboardSummary() {
  return window['go']['main']['App']['DashboardSummary']();
}

export function GetSaleDetail(arg1) {
  return window['go']['main']['App']['GetSaleDetail'](arg1);
}

export function GetSyncStatus() {
  return window['go']['main']['App']['GetSyncStatus']();
}

export function ListCategories() {
  return window['go']['main']['App']['ListCategories']();
}

export function ListLowStockProducts() {
  return window['go']['main']['App']['ListLowStockProducts']();
}

export function ListPendingSyncRecords(arg1) {
  return window['go']['main']['App']['ListPendingSyncRecords'](arg1);
}

export function ListProducts() {
  return window['go']['main']['App']['ListProducts']();
}

export function ListSales(arg1) {
  return window['go']['main']['App']['ListSales'](arg1);
}

export function ListSettings() {
  return window['go']['main']['App']['ListSettings']();
}

export function ListStaff() {
  return window['go']['main']['App']['ListStaff']();
}

export function MarkSyncRecordsSynced(arg1) {
  return window['go']['main']['App']['MarkSyncRecordsSynced'](arg1);
}

export function PullMutationsForDevice(arg1, arg2, arg3) {
  return window['go']['main']['App']['PullMutationsForDevice'](arg1, arg2, arg3);
}

export function SeedDemoData() {
  return window['go']['main']['App']['SeedDemoData']();
}

export function StartMPesaCharge(arg1) {
  return window['go']['main']['App']['StartMPesaCharge'](arg1);
}

export function StartupStatus() {
  return window['go']['main']['App']['StartupStatus']();
}

export function UpsertSetting(arg1) {
  return window['go']['main']['App']['UpsertSetting'](arg1);
}

export function VerifyMPesaCharge(arg1) {
  return window['go']['main']['App']['VerifyMPesaCharge'](arg1);
}

export function VerifyStaffPIN(arg1) {
  return window['go']['main']['App']['VerifyStaffPIN'](arg1);
}
