// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {main} from '../models';

export function AdjustStock(arg1:store.StockAdjustmentInput):Promise<void>;

export function ApplyIncomingMutations(arg1:string,arg2:Array<store.SyncMutation>):Promise<store.SyncPushResponse>;

export function AuthenticateStaff(arg1:store.StaffLoginInput):Promise<store.Staff>;

export function BackendHealth():Promise<store.HealthStatus>;

export function BootstrapBusiness(arg1:store.BootstrapInput):Promise<void>;

export function CreateCategory(arg1:store.CreateCategoryInput):Promise<store.Category>;

export function CreateProduct(arg1:store.CreateProductInput):Promise<store.Product>;

export function CreateSale(arg1:store.CreateSaleInput):Promise<store.SaleDetail>;

export function CreateStaff(arg1:store.CreateStaffInput):Promise<store.Staff>;

export function DashboardSummary():Promise<store.DashboardSummary>;

export function GetSaleDetail(arg1:string):Promise<store.SaleDetail>;

export function GetSyncStatus():Promise<main.AppSyncStatus>;

export function ListCategories():Promise<Array<store.Category>>;

export function ListLowStockProducts():Promise<Array<store.ProductStockView>>;

export function ListPendingSyncRecords(arg1:number):Promise<Array<store.SyncRecord>>;

export function ListProducts():Promise<Array<store.Product>>;

export function ListSales(arg1:number):Promise<Array<store.Sale>>;

export function ListSettings():Promise<Array<store.Setting>>;

export function ListStaff():Promise<Array<store.Staff>>;

export function MarkSyncRecordsSynced(arg1:Array<string>):Promise<void>;

export function PullMutationsForDevice(arg1:string,arg2:string,arg3:number):Promise<Array<store.SyncMutation>>;

export function SeedDemoData():Promise<store.SeedResult>;

export function StartMPesaCharge(arg1:store.StartMPesaChargeInput):Promise<store.MPesaChargeSession>;

export function StartupStatus():Promise<string>;

export function UpsertSetting(arg1:store.Setting):Promise<void>;

export function VerifyMPesaCharge(arg1:string):Promise<store.MPesaChargeStatus>;

export function VerifyStaffPIN(arg1:store.PINVerificationInput):Promise<boolean>;
